# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'SentirLite' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SentirLite

  pod 'MobileVLCKit'
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'Kingfisher'
  pod "Jelly"
  pod 'FSCalendar'
  pod 'JVFloatLabeledTextField'
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
  pod 'SCLAlertView'
  pod 'SquareMosaicLayout'
  pod 'Fabric'
  pod 'Crashlytics'
#  pod 'VGPlayer', '~> 0.1.5'
  pod 'Google-Mobile-Ads-SDK'
  pod 'DLRadioButton', '~> 1.4'
end
